[package]
name = "web_script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "0.20.0"
serde_json = "1.0.116"
threadpool = "1.8.1"
